name: Update Market Data

on:
  schedule:
    - cron: '*/5 3-10 * * 1-5' # Market hours me har 5 minute auto run
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pyotp

      - name: Run Market Screener
        run: |
          python fetch_data.py

      - name: Save and Commit Data to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          if ! git diff --staged --quiet; then
            git commit -m "Real live market data updated"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes"
          fi
